call plug#begin('~/.config/nvim/plugged')
" Themes
Plug 'joshdick/onedark.vim'
" Visual
Plug 'lilydjwg/colorizer'
" Functional
Plug 'sheerun/vim-polyglot'
Plug 'easymotion/vim-easymotion'
Plug 'scrooloose/nerdtree'
Plug 'christoomey/vim-tmux-navigator'
Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'
call plug#end()
